Vagrant.configure("2") do |config|

  config.vm.box = "dummy"
  config.vm.provider :aws do |aws, override|
    ## get user account credentials from the environment (do not hardcode )
    secret_key = `aws configure get aws_secret_access_key`
    access_key = `aws configure get aws_access_key_id`   
    aws.access_key_id = access_key.chomp
    aws.secret_access_key = secret_key.chomp

    #machine specifics
    aws.ami = "ami-ae1b18c6"
    aws.region = "us-east-1"
    aws.instance_type = "m4.large"
    aws.keypair_name = "MUTHU_KP1"
    aws.security_groups = [ "sg-612bce1a" ]
    override.ssh.private_key_path = '/Users/Muthu/.ssh/MUTHU_KP1.pem'
    override.ssh.username = "ec2-user"
    aws.associate_public_ip = true
    aws.subnet_id = "subnet-8a51cffc"
    #aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => 20 }]
    aws.tags = {
      'Name' => 'DevOpsDay Demo VM',
      'VM Started At' => 'Demo Time: ' + Time.new.localtime.to_s
    }
  end

end
