# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "puppetlabs/centos-6.6-64-puppet"
  config.vm.network "private_network", ip: "192.168.33.12"

  config.vm.provision :puppet do |puppet|
    puppet.environment_path = "environments"
    puppet.environment = "test"
    puppet.options = "--verbose --hiera_config /vagrant/hiera.yaml"
  end

end 
